services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=flight-management'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=flight-management'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=Supervisor'
    ports:
      - '5432:5432'
